make the fucking versioning work
```
error: failed to select a version for `parity-snappy-sys`.
    ... required by package `parity-rocksdb-sys v0.5.6 (https://github.com/outliners/rust-rocksdb#0475f746)`
    ... which is depended on by `parity-rocksdb v0.5.1 (https://github.com/outliners/rust-rocksdb#0475f746)`
    ... which is depended on by `kvdb-rocksdb v0.1.0 (/home/isaac/parity4MCIP8/util/kvdb-rocksdb)`
    ... which is depended on by `ethcore v1.9.0 (/home/isaac/parity4MCIP8/ethcore)`
    ... which is depended on by `ethcore-light v1.9.0 (/home/isaac/parity4MCIP8/ethcore/light)`
    ... which is depended on by `ethsync v1.9.0 (/home/isaac/parity4MCIP8/sync)`
    ... which is depended on by `ethcore-secretstore v1.0.0 (/home/isaac/parity4MCIP8/secret_store)`
    ... which is depended on by `parity v1.9.5 (/home/isaac/parity4MCIP8)`
versions that meet the requirements `^0.1.1` are: 0.1.2, 0.1.1

the package `parity-snappy-sys` links to the native library `snappy`, but it conflicts with a previous package which links to `snappy` as well:
package `parity-snappy-sys v0.1.2 (https://github.com/paritytech/rust-snappy#1195dfa4)`
    ... which is depended on by `parity-snappy v0.1.0 (https://github.com/paritytech/rust-snappy#1195dfa4)`
    ... which is depended on by `ethcore v1.9.0 (/home/isaac/parity4MCIP8/ethcore)`
    ... which is depended on by `ethcore-light v1.9.0 (/home/isaac/parity4MCIP8/ethcore/light)`
    ... which is depended on by `ethsync v1.9.0 (/home/isaac/parity4MCIP8/sync)`
    ... which is depended on by `ethcore-secretstore v1.0.0 (/home/isaac/parity4MCIP8/secret_store)`
    ... which is depended on by `parity v1.9.5 (/home/isaac/parity4MCIP8)`

failed to select a version for `parity-snappy-sys` which could resolve this conflict
```